import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "../context/AuthContext";
import { Header } from "../components/common";
import { Footer } from "../components/common/Footer";
import { ReactLenis } from "../util/lenis";
import { ToastProvider } from "../components/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Country Finder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContextProvider>
          <ReactLenis root>
            <ToastProvider>
              <Header />
              {children}
              <Footer />
            </ToastProvider>
          </ReactLenis>
        </AuthContextProvider>
      </body>
    </html>
  );
}
